webscrapper/frontend/webscrapper_app/config/routes.rb
Rails.application.routes.draw do

  root 'resto_scrapper#home'
  resources :reviews

  post 'reviews/book' => 'reviews#book', as: :book_res
  post 'reviews/yelp' => 'reviews#yelp', as: :yelp
  post 'reviews/fs' => 'reviews#fs', as: :fs
  post 'reviews/ta' => 'reviews#ta', as: :ta
  resources :usages

end

webscrapper/frontend/webscrapper_app/app/models/foursquare_review.rb
class FoursquareReview < ActiveRecord::Base
end

webscrapper/frontend/webscrapper_app/app/models/review.rb
class Review < ActiveRecord::Base

	def self.search(search)
    if search
      search = search.downcase
      where("lower(name) like :search",search2: "#{search}",search: "%#{search}%")
    else
      all
    end
end
end

webscrapper/frontend/webscrapper_app/app/models/tripadvisor_review.rb
class TripadvisorReview < ActiveRecord::Base
end

webscrapper/frontend/webscrapper_app/app/models/usage.rb
class Usage < ActiveRecord::Base
end

webscrapper/frontend/webscrapper_app/app/models/yelp_review.rb
class YelpReview < ActiveRecord::Base
end

webscrapper/frontend/webscrapper_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_cache_headers

  private

  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

webscrapper/frontend/webscrapper_app/app/controllers/resto_scrapper_controller.rb
class RestoScrapperController < ApplicationController
	def home
	end
end

webscrapper/frontend/webscrapper_app/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_review
	def index
		@restaurants = Review.search(params[:search]).page(params[:page]).per(4)
    end

    def show
    	@review = Review.find(params[:id])
        res_id = @review.res_id
        usage = Usage.find_by_res_id(res_id)
        show_count = usage.show_count
        show_count = show_count + 1
        usage.update(show_count: show_count)
    	@yelp_id = @review.yelp_id
    	@ta_id = @review.ta_id
    	@fs_id = @review.fs_id
    	@yelp_review = YelpReview.find_by_yelp_id(@yelp_id)
    	@ta_review = TripadvisorReview.find_by_ta_id(@ta_id)
    	@fs_review = FoursquareReview.find_by_fs_id(@fs_id)
    	@aggregate = ( @yelp_review.rating*@yelp_review.ratings_count +
                     @ta_review.rating*@ta_review.ratings_count + 
                     ( @fs_review.rating / 2 )*@fs_review.ratings_count )/ (
                     @yelp_review.ratings_count + @ta_review.ratings_count +
                     @fs_review.ratings_count)
    	@aggregate = @aggregate.round(1)

        yelp_reviews = JSON.parse(("{\"reviews\":" + @yelp_review.reviews + "}" ).gsub("=>", ":"))
        ta_reviews = JSON.parse(("{\"reviews\":" + @ta_review.reviews + "}").gsub("=>", ":"))
        fs_reviews = JSON.parse(("{\"reviews\":" + @fs_review.reviews + "}").gsub("=>", ":"))

        @yelp_review_text = []
        @yelp_review_rating = []
        for i in 0..yelp_reviews['reviews'].count - 1
            @yelp_review_text[i] = yelp_reviews['reviews'][i]['review']
            @yelp_review_rating[i] = yelp_reviews['reviews'][i]['scale']
        end

        @ta_review_text = []
        @ta_review_rating = []
        for i in 0..ta_reviews['reviews'].count - 1
            @ta_review_text[i] = ta_reviews['reviews'][i]['review']
            @ta_review_rating[i] = ta_reviews['reviews'][i]['scale']
        end

        @fs_review_text = []
        @fs_review_rating = []
        for i in 0..fs_reviews['reviews'].count - 1
            @fs_review_text[i] = fs_reviews['reviews'][i]['review']
            @fs_review_rating[i] = fs_reviews['reviews'][i]['scale']
        end


        #negative reviews
        yelp_neg_reviews = JSON.parse(("{\"neg_reviews\":" + @yelp_review.neg_reviews + "}" ).gsub("=>", ":"))
        @yelp_neg_review_text = []
        @yelp_neg_review_rating = []
        for i in 0..yelp_neg_reviews['neg_reviews'].count - 1
            @yelp_neg_review_text[i] = yelp_neg_reviews['neg_reviews'][i]['review']
            @yelp_neg_review_rating[i] = yelp_neg_reviews['neg_reviews'][i]['scale']
        end

       @map = ['dummy']
       @hash = Gmaps4rails.build_markers(@map) do |user, marker|
           marker.lat @review.lat
           marker.lng @review.lon
       end




    end
    def set_review

    end

    def book
        @review = Review.find(params[:id])
        res_id = @review.res_id
        usage = Usage.find_by_res_id(res_id)
        book_count = usage.book_count
        book_count = book_count + 1
        usage.update(book_count: book_count)
        redirect_to @review.res_url
    end

    def yelp
        @review = Review.find(params[:id])
        res_id = @review.res_id
        usage = Usage.find_by_res_id(res_id)
        yelp_count = usage.yelp_count
        yelp_count = yelp_count + 1
        usage.update(yelp_count: yelp_count)
        @yelp_id = @review.yelp_id
        @yelp_review = YelpReview.find_by_yelp_id(@yelp_id)
        redirect_to @yelp_review.url

    end

    def fs
        @review = Review.find(params[:id])
        res_id = @review.res_id
        usage = Usage.find_by_res_id(res_id)
        fs_count = usage.fs_count
        fs_count = fs_count + 1
        usage.update(fs_count: fs_count)
        @fs_id = @review.fs_id
        @fs_review = FoursquareReview.find_by_fs_id(@fs_id)
        redirect_to @fs_review.url

    end

    def ta
        @review = Review.find(params[:id])
        res_id = @review.res_id
        usage = Usage.find_by_res_id(res_id)
        ta_count = usage.ta_count
        ta_count = ta_count + 1
        usage.update(ta_count: ta_count)
        @ta_id = @review.ta_id
        @ta_review = TripadvisorReview.find_by_ta_id(@ta_id)
        redirect_to @ta_review.url
        
    end
end

webscrapper/frontend/webscrapper_app/app/controllers/usages_controller.rb
class UsagesController < ApplicationController
	def index
		@res_names = []
		@res_ids = []
		@show_counts = []
		@yelp_counts = []
		@fs_counts = []
		@ta_counts = []
		@booking_counts = []

		count = 0
		Usage.all.each do |usage|
			@res_ids[count] = usage.res_id
			@show_counts[count] = usage.show_count
			@yelp_counts[count] = usage.yelp_count
			@fs_counts[count] = usage.fs_count
			@ta_counts[count] = usage.ta_count
			@booking_counts[count] = usage.book_count
			@res_names[count] = Review.find_by_res_id(usage.res_id).name
			count = count + 1
		end

		@total_count = count-1

		@total_show_count = 0
		@total_redirect_count = 0
		@total_booking_count = 0

		for i in 0..count-1
			@total_show_count = @total_show_count + @show_counts[i]
			@total_redirect_count = @total_redirect_count + @yelp_counts[i]
			@total_redirect_count = @total_redirect_count + @fs_counts[i]
			@total_redirect_count = @total_redirect_count + @ta_counts[i]
			@total_booking_count = @total_booking_count + @booking_counts[i]
		end

		@redirect_count_percentage = ((@total_redirect_count.to_f/@total_show_count.to_f)*100.0).round(2)
		@booking_count_percentage = ((@total_booking_count.to_f/@total_show_count.to_f)*100.0).round(2)
    end
end

webscrapper/frontend/webscrapper_app/app/helpers/application_helper.rb
module ApplicationHelper
end

webscrapper/frontend/webscrapper_app/app/helpers/resto_scrapper_helper.rb
module RestoScrapperHelper
end

webscrapper/frontend/webscrapper_app/app/helpers/reviews_helper.rb
module ReviewsHelper
end

webscrapper/frontend/webscrapper_app/app/helpers/usages_helper.rb
module UsagesHelper
end

webscrapper/frontend/webscrapper_app/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand pull-center" href="/">RestoScrapper</a>
    </div>
    <!-- <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/books">Books</a></li>
      </ul>

      <p class="navbar-text pull-right">
        </div>
  </div> -->
</nav>

webscrapper/frontend/webscrapper_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebscrapperApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <% if message_type == "success" %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% else %>
            <div class="alert alert-info"><%= message %></div>
        <% end %>
    <% end %>
    <%= yield %>
  </div>

 
<script src="//railsgirls.com/assets/bootstrap.js"></script>


</body>
</html>

webscrapper/frontend/webscrapper_app/app/views/resto_scrapper/home.html.erb
<div class="jumbotron vertical-center">
	<%= form_tag(reviews_path, :method => "get", class: "") do %>
	<div class="row">
	<div class="col-lg-12">
    <div class="input-group ">
      <%= text_field_tag :search,params[:search], class: "form-control input-lg", placeholder: "Search Restaurants", :size => "30" %>
      <span class="input-group-btn">
        <button class="btn btn-default input-lg" type="submit">Search!</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->
<% end %> 
</div>

webscrapper/frontend/webscrapper_app/app/views/reviews/index.html.erb
<h1>Listing Restaurants</h1>
<% if @restaurants.present? %>
	<table class="table">
  	<thead>
  		<tr>
  			<th></th>
  			<th>Name</th>	
  			<th>Link</th>
  		</tr>
  	</thead>
  	<tbody>
  		<% @restaurants.each do |res| %>
  			<tr>
          		<td><%= link_to (image_tag( res.photo_url, :size => "100x100", class: "img-thumbnail")), review_path(res) %></td>
  				<td><%= res.name %></td>
  				<td><%= link_to 'Show Reviews', review_path(res) %></td>
  			</tr>
  		<% end %>

  	</tbody>
  </table>
  <nav>
  <ul class="pagination">
  <%= paginate @restaurants %>
  </ul>
</nav>
  <% else %>
    <p>There are no restaurants with the search term(s) <%= params[:search] %>.</p>
<% end %>

webscrapper/frontend/webscrapper_app/app/views/reviews/show.html.erb
<script type="text/javascript">$(function() {
    $('span.stars').stars();
});</script>

<script type="text/javascript">$(function() {
    $('span.stars10').stars10();
});</script>

<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<h2>
  
  <%= @review.name %>
</h2>

<script type="text/javascript">
analytics.page('View Restaurant');
var link = document.getElementById('book-button');


</script>
<div class = "row">
  <div class = "col-md-4">
    <div class = "img-thumbnail">
    <%= image_tag @review.photo_url%>
    </div>


    <br>
    <br>
    <p>
      <!-- <strong><%=link_to  "Yelp Rating:" , @yelp_review.url%></strong> -->
      <strong><%=link_to  "Yelp Rating:" , {:controller => "reviews", :action => "yelp", :id=> @review.id }, method: :post%></strong>
      <%= @yelp_review.rating %> / <%= @yelp_review.scale %> (<%= @yelp_review.ratings_count %> ratings)<span class="stars"><%= @yelp_review.rating %></span>
    </p>

    <p>
      <!-- <strong><%=link_to  "Trip Advisor Rating:", @ta_review.url %> </strong> -->
       <strong><%=link_to  "Trip Advisor Rating:" , {:controller => "reviews", :action => "ta", :id=> @review.id }, method: :post%></strong>
      <%= @ta_review.rating %> / <%= @ta_review.scale %> (<%= @ta_review.ratings_count %> ratings)<span class="stars"><%= @ta_review.rating %></span>
    </p>
    <p>
     <!--  <strong><%=link_to "Foursquare Rating:", @fs_review.url %> </strong> -->
       <strong><%=link_to  "Foursquare Rating:" , {:controller => "reviews", :action => "fs", :id=> @review.id }, method: :post%></strong>
      <%= @fs_review.rating %> / <%= @fs_review.scale %> (<%= @fs_review.ratings_count %> ratings)<span class="stars10"><%= @fs_review.rating %></span>
    </p>
    <p>
      <strong>Average Rating: </strong>
      <%= @aggregate %> / 5 <span class="stars"><%= @aggregate %></span>
    </p>
    <br>
    <!-- <a class="btn btn-primary" id = "book-button" href= "<%=@review.res_url%>" role="button">Book Now!</a> -->
    <%= button_to "Book Now!", {:controller => "reviews", :action => "book", :id=> @review.id }, {class: 'btn btn-primary'}%>
  </div>
  <div class = "img-thumbnail">
  <div id="map" style='width: 380px; height: 380px;' class = "col-md-4">

  </div>
</div>
</div>


<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {maxZoom: 18}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

<br/>
<div class = "row">
  <div class="col-md-6">
    <h3>Top Reviews</h3>
    <table class = "table">
      <thead>
        <tr>
        <th>Source</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Comments</th>
      </tr>
      </thead>
      <tbody>
        <tr>
          <td>Yelp</td>
          <td>
            <ul>
              <%
                n = @yelp_review_text.count
                if(n> 3)
                  n = 3;
                end
              %>
              <% n.times do |i|%>
              <li> <%=@yelp_review_text[i] %><br><span class="stars"><%=@yelp_review_rating[i] %></span></li>
              <% end %>
            </ul>
          </td>
        </tr>
        <tr>
          <td>Trip Advisor</td>
          <td>
            <ul> 
              <%
                n = @ta_review_text.count
                if(n> 3)
                  n = 3;
                end
              %>
              <% n.times do |i|%>
              <li><%=@ta_review_text[i] %><br><span class="stars"><%=@ta_review_rating[i] %></span></li>
              <% end %>
            </ul>
          </td>
        </tr>
        <tr>
          <td>Four Square</td>
          <td>
            <ul> 
              <%
                n = @fs_review_text.count
                if(n> 3)
                  n = 3;
                end
              %>
              <% n.times do |i|%>
              <li><%=@fs_review_text[i] %><br><span class="stars10"><%=@fs_review_rating[i] %></span></li>
              <% end %>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class = "col-md-6">

    <h3>Negative Reviews</h3>
    <table class = "table">
      <thead>
        <tr>
        <!-- <th>Score</th> -->
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Comments</th>
      </tr>
      </thead>
      <tbody>
        <tr>
          <!-- <td>Yelp</td> -->
          <td>
            <ul>
              <%
                n = @yelp_neg_review_text.count
                if(n> 3)
                  n = 3;
                end
              %>
              <% n.times do |i|%>
              <li> <%=@yelp_neg_review_text[i] %><br><span class="stars"><%=@yelp_neg_review_rating[i] %></span></li>
              <% end %>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<hr>

  </p>
  <%= link_to "View all Restaurants", reviews_path %>
  </p>
  <p>
  <%= link_to "Home", root_path %>
  </p>
 

webscrapper/frontend/webscrapper_app/app/views/usages/index.html.erb
<h1>Website usage history</h1>

</br>

<table border="4" >
	<col width="220">
	<col width="100">
	<col width="100">
	<col width="100">
	<col width="100">
	<col width="100">
	<tr>
		<th>Restaurant Name</th>
		<th>Hit Count</th>
		<th>Yelp Redirect Count</th>
		<th>Trip Advisor Redirect Count</th>
		<th>Foursquare Redirect Count</th>
		<th>Booking Count</th>
	</tr>
    <% for i in 0..@total_count %>
        <tr>
    	    <td><%= @res_names[i] %></td>
    	    <td><%= @show_counts[i] %></td>
    	    <td><%= @yelp_counts[i] %></td>
    	    <td><%= @ta_counts[i] %></td>
    	    <td><%= @fs_counts[i] %></td>
    	    <td><%= @booking_counts[i] %></td>
        </tr>
    <% end %>
</table>
<br/>
<font color = "green"><b><%= "Total hit count: " + @total_show_count.to_s %></b></font><br/>
<font color = "green"><b><%= "Total redirect count: " + @total_redirect_count.to_s %></b></font><br/>
<font color = "green"><b><%= "Total booking count: " + @total_booking_count.to_s %></b></font><br/>
<font color = "green"><b><%= "Total redirect percentage: " + @redirect_count_percentage.to_s %></b></font><br/>
<font color = "green"><b><%= "Total booking percentage: " + @booking_count_percentage.to_s %></b></font><br/>